### ISSUE TITLE
Angular 4 support

### ISSUE THREAD

**Issue by AntonEmery** [AntonEmery/angular2-twig#1]
@manekinekko here is my basic project. I took your code and tried to integrate it into a angular cli project, I hope that is ok.  :)  

I am basically trying to build an angular app where each component template file is a twig template sitting on S3. The app pulls in other content from a JSON file, and compiles the website. In this way I can have one angular project, ideally it would reference the location of a particular Twig template from a config file, and it can build out any number of site variations based on the number of templates. I don't even know if such a thing is possible, but I figured I would give it a shot.

Alot of this is new to me, and I may not have included your various `twig-decorator` files correctly. I've got a test component in `src/app/components/test` where I am trying to set the Twig template as a string to start.

My initial problem in getting the app to compile is in `twig-decorator.ts`.

```
import {
  Component
} from '@angular/core';

import {
  PromiseWrapper
} from 'angular2/src/facade/async';
```

I changed that first import statement on line 1 to reflect the current version of angular, but I cannot seem to find a similar thing for the promise wrapper in the second import statement. 

Thanks in advance!  :)

**Comment by manekinekko** [comment]
Hi @AntonEmery 

I just updated my lib. It's working as expected with Angular v2+.
You can install it from npm. See the [readme](https://github.com/manekinekko/angular-twig#install).

**Comment by manekinekko** [comment]
See an [example here](https://github.com/manekinekko/angular-twig-demo/blob/9ca1d0c004c28bcb448c898155fe7a36cad52b19/src/app/components/test/test.component.ts).

**Comment by AntonEmery** [comment]
Thanks @manekinekko !  That worked like a charm. Do you know if it is possible to load a Twig template sitting on S3?  I thought you had done something similar in this [plnkr](http://plnkr.co/edit/K0MohmywZpn5aSVHtYad?p=preview), but I realize now you are getting the template from `index.html`

**Comment by AntonEmery** [comment]
@manekinekko nevermind, I think i've got it sorted out.  :)
